"""Generate this repository's pyproject.toml from scipy's dependency groups.

    python sync_dependency_groups.py <scipy checkout> > pyproject.toml

The wheel and sdist builds only ever install four of scipy's dependency groups, but a
`uv.lock` covers a whole project - locking scipy's own pyproject.toml pulls in `doc`,
`dev`, `typecheck` and friends too, which is roughly 180 packages and 3500 lines of lock
file that never get installed. So instead we lock a project that declares just the groups
we need, copied verbatim out of scipy's pyproject.toml by this script.

`check_lock` in wheels.yml regenerates the file and diffs it against the committed one.
That is what catches scipy changing its build or test requirements - the same job
`uv lock --check` used to do, minus the false alarms from scipy bumping its version
string or editing groups we don't install.
"""
import sys
import tomllib

# the groups the wheel and sdist builds install; see cibw_before_build.sh,
# cibw_before_test.sh and the build_sdist job in wheels.yml
GROUPS = ["build", "test-core", "openblas32", "openblas64"]

HEADER = """\
# Generated by tools/sync_dependency_groups.py - do not edit.
#
# This is not a real package. It exists so that uv.lock can pin the dependency groups
# that the wheel and sdist builds install, without dragging in the rest of scipy's
# dependency groups. Regenerate it with tools/update_lock.sh.
"""


def flatten(groups, name):
    """Expand a dependency group, inlining any `include-group` entries."""
    requirements = []
    for item in groups[name]:
        if isinstance(item, dict):
            requirements += flatten(groups, item["include-group"])
        else:
            requirements.append(item)
    # dict.fromkeys rather than set(), to keep the order stable across runs
    return list(dict.fromkeys(requirements))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__.splitlines()[2].strip())

    with open(f"{sys.argv[1]}/pyproject.toml", "rb") as f:
        scipy = tomllib.load(f)

    out = [HEADER, "[project]", 'name = "scipy-release-deps"', 'version = "0"',
           f'requires-python = "{scipy["project"]["requires-python"]}"',
           "dependencies = []", "",
           "[tool.uv]", "# a virtual project: there is nothing here to build or install",
           "package = false", "", "[dependency-groups]"]
    for group in GROUPS:
        requirements = ",\n    ".join(
            f'"{r}"' for r in flatten(scipy["dependency-groups"], group)
        )
        out.append(f"{group} = [\n    {requirements},\n]")

    print("\n".join(out))


if __name__ == "__main__":
    main()
